### ISSUE TITLE
PHP code is modified after beautify

### ISSUE THREAD

**Issue by kwyatt242** [Andr3as/Codiad-Beautify#9]
Every time I beautify, I must go back and correct my code since beautify makes an "update" that breaks the app.

original -
$image=new Imagick();

after beautify -
$image=newImagick();

**Comment by kwyatt242** [comment]
Just to add to this, here is another scenario where this bug is evident -

original -
$usersTimezone=new DateTimeZone($userStatus['userTimezone']);
$l10nDate=new DateTime($msTimestamp);

after beautify -
$usersTimezone=newDateTimeZone($userStatus['userTimezone']);
$l10nDate=newDateTime($msTimestamp);

Perhaps it is doing this with anything using the 'new' keyword.. I haven't tested for other scenarios.

**Comment by kwyatt242** [comment]
I updated the ACE components hoping for a fix but it made no difference.
https://github.com/Codiad/Codiad/wiki/Tutorial:-How-to-manually-upgrade-to-latest-ACE-version

**Comment by Andr3as** [comment]
This plugin uses its own version ([file](https://github.com/Andr3as/Codiad-Beautify/blob/master/libs/ext-beautify.js)) of the necessary ace extension because of some dirty fixes. There is still no update of the original extension ([file](https://github.com/ajaxorg/ace-builds/blob/master/src/ext-beautify.js)) since the initial commit of this plugin.

I created a dirty fix (7d29473) for your problem, but I'm not happy with it.

**Comment by Andr3as** [comment]
See #10 for further developments.
